// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YeniSalon.Data;

#nullable disable

namespace YeniSalon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216193135_UpdateAIEgzersizOneri")]
    partial class UpdateAIEgzersizOneri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YeniSalon.Models.AIEgzersizOneri", b =>
                {
                    b.Property<int>("OneriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OneriId"));

                    b.Property<string>("AIGorselUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIYaniti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Boy")
                        .HasColumnType("int");

                    b.Property<int?>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GirilenBilgi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Hedef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IstekTipi")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Yas")
                        .HasColumnType("int");

                    b.HasKey("OneriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AIEgzersizOnerileri");
                });

            modelBuilder.Entity("YeniSalon.Models.Antrenor", b =>
                {
                    b.Property<int>("AntrenorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntrenorId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<int>("DeneyimYili")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HaftalikCalismaSaati")
                        .HasColumnType("int");

                    b.Property<string>("ProfilFotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaatlikUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalonId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UzmanlikAlanlari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntrenorId");

                    b.HasIndex("SalonId");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique();

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("YeniSalon.Models.AntrenorHizmet", b =>
                {
                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("AntrenorId", "HizmetId");

                    b.HasIndex("HizmetId");

                    b.ToTable("AntrenorHizmetler");
                });

            modelBuilder.Entity("YeniSalon.Models.AntrenorUzmanlik", b =>
                {
                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<int>("UzmanlikId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("AntrenorId", "UzmanlikId");

                    b.HasIndex("UzmanlikId");

                    b.ToTable("AntrenorUzmanliklar");
                });

            modelBuilder.Entity("YeniSalon.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("Boy")
                        .HasColumnType("int");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Kilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilFotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UyelikBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UyelikBitis")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UyelikTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("YeniSalon.Models.Hizmet", b =>
                {
                    b.Property<int>("HizmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("HizmetAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HizmetId");

                    b.HasIndex("SalonId");

                    b.ToTable("Hizmetler");

                    b.HasData(
                        new
                        {
                            HizmetId = 1,
                            Aciklama = "Bire bir antrenör eşliğinde kişiye özel antrenman programı",
                            AktifMi = true,
                            HizmetAdi = "Kişisel Antrenman",
                            Kategori = "Fitness",
                            SalonId = 1,
                            SureDakika = 60,
                            Ucret = 150.00m
                        },
                        new
                        {
                            HizmetId = 2,
                            Aciklama = "Grup halinde yapılan fitness dersi",
                            AktifMi = true,
                            HizmetAdi = "Grup Fitness",
                            Kategori = "Fitness",
                            SalonId = 1,
                            SureDakika = 45,
                            Ucret = 50.00m
                        },
                        new
                        {
                            HizmetId = 3,
                            Aciklama = "Esneklik ve rahatlama için yoga seansı",
                            AktifMi = true,
                            HizmetAdi = "Yoga Dersi",
                            Kategori = "Yoga",
                            SalonId = 1,
                            SureDakika = 60,
                            Ucret = 80.00m
                        },
                        new
                        {
                            HizmetId = 4,
                            Aciklama = "Profesyonel boks dersi.",
                            AktifMi = true,
                            HizmetAdi = "Boks Dersi",
                            Kategori = "Boks",
                            SalonId = 1,
                            SureDakika = 90,
                            Ucret = 130.00m
                        },
                        new
                        {
                            HizmetId = 5,
                            Aciklama = "Esneklik ve rahatlama için Pilates seansı",
                            AktifMi = true,
                            HizmetAdi = "Pilates Dersi",
                            Kategori = "Pilates",
                            SalonId = 1,
                            SureDakika = 60,
                            Ucret = 100.00m
                        },
                        new
                        {
                            HizmetId = 6,
                            Aciklama = "Alanında uzman eğitmen ile karate dersi",
                            AktifMi = true,
                            HizmetAdi = "Karate Dersi",
                            Kategori = "Karate",
                            SalonId = 1,
                            SureDakika = 75,
                            Ucret = 120.00m
                        });
                });

            modelBuilder.Entity("YeniSalon.Models.MusaitlikSaati", b =>
                {
                    b.Property<int>("MusaitlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusaitlikId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.HasKey("MusaitlikId");

                    b.HasIndex("AntrenorId");

                    b.ToTable("MusaitlikSaatleri");
                });

            modelBuilder.Entity("YeniSalon.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"));

                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Not")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuId");

                    b.HasIndex("AntrenorId");

                    b.HasIndex("HizmetId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("YeniSalon.Models.Salon", b =>
                {
                    b.Property<int>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonId"));

                    b.Property<TimeSpan>("AcilisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("KapanisSaati")
                        .HasColumnType("time");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalonId");

                    b.ToTable("Salonlar");

                    b.HasData(
                        new
                        {
                            SalonId = 1,
                            AcilisSaati = new TimeSpan(0, 6, 0, 0, 0),
                            Adres = "Serdivan / Sakarya",
                            Email = "merkez@sporsalonu.com",
                            KapanisSaati = new TimeSpan(0, 23, 0, 0, 0),
                            SalonAdi = "Merkez Spor Salonu",
                            Telefon = "(555) 555 55 55"
                        });
                });

            modelBuilder.Entity("YeniSalon.Models.Uzmanlik", b =>
                {
                    b.Property<int>("UzmanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzmanlikId"));

                    b.Property<string>("UzmanlikAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UzmanlikId");

                    b.ToTable("Uzmanliklar");

                    b.HasData(
                        new
                        {
                            UzmanlikId = 1,
                            UzmanlikAdi = "Kas Geliştirme"
                        },
                        new
                        {
                            UzmanlikId = 2,
                            UzmanlikAdi = "Kilo Verme"
                        },
                        new
                        {
                            UzmanlikId = 3,
                            UzmanlikAdi = "Fonksiyonel Antrenman"
                        },
                        new
                        {
                            UzmanlikId = 4,
                            UzmanlikAdi = "Yoga"
                        },
                        new
                        {
                            UzmanlikId = 5,
                            UzmanlikAdi = "Pilates"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YeniSalon.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YeniSalon.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YeniSalon.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YeniSalon.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YeniSalon.Models.AIEgzersizOneri", b =>
                {
                    b.HasOne("YeniSalon.Models.ApplicationUser", "Kullanici")
                        .WithMany("AIOnerileri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YeniSalon.Models.Antrenor", b =>
                {
                    b.HasOne("YeniSalon.Models.Salon", "Salon")
                        .WithMany("Antrenorler")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("YeniSalon.Models.AntrenorHizmet", b =>
                {
                    b.HasOne("YeniSalon.Models.Antrenor", "Antrenor")
                        .WithMany("AntrenorHizmetler")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YeniSalon.Models.Hizmet", "Hizmet")
                        .WithMany("AntrenorHizmetler")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("YeniSalon.Models.AntrenorUzmanlik", b =>
                {
                    b.HasOne("YeniSalon.Models.Antrenor", "Antrenor")
                        .WithMany("AntrenorUzmanliklar")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YeniSalon.Models.Uzmanlik", "Uzmanlik")
                        .WithMany("AntrenorUzmanliklar")
                        .HasForeignKey("UzmanlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Uzmanlik");
                });

            modelBuilder.Entity("YeniSalon.Models.Hizmet", b =>
                {
                    b.HasOne("YeniSalon.Models.Salon", "Salon")
                        .WithMany("HizmetTurleri")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("YeniSalon.Models.MusaitlikSaati", b =>
                {
                    b.HasOne("YeniSalon.Models.Antrenor", "Antrenor")
                        .WithMany("MusaitlikSaatleri")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");
                });

            modelBuilder.Entity("YeniSalon.Models.Randevu", b =>
                {
                    b.HasOne("YeniSalon.Models.Antrenor", "Antrenor")
                        .WithMany("Randevular")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YeniSalon.Models.Hizmet", "Hizmet")
                        .WithMany("Randevular")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YeniSalon.Models.ApplicationUser", "Kullanici")
                        .WithMany("Randevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YeniSalon.Models.Antrenor", b =>
                {
                    b.Navigation("AntrenorHizmetler");

                    b.Navigation("AntrenorUzmanliklar");

                    b.Navigation("MusaitlikSaatleri");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("YeniSalon.Models.ApplicationUser", b =>
                {
                    b.Navigation("AIOnerileri");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("YeniSalon.Models.Hizmet", b =>
                {
                    b.Navigation("AntrenorHizmetler");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("YeniSalon.Models.Salon", b =>
                {
                    b.Navigation("Antrenorler");

                    b.Navigation("HizmetTurleri");
                });

            modelBuilder.Entity("YeniSalon.Models.Uzmanlik", b =>
                {
                    b.Navigation("AntrenorUzmanliklar");
                });
#pragma warning restore 612, 618
        }
    }
}
